### ISSUE TITLE
ERROR: Encountered an error while flashing argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by floean** [badabing2005/PixelFlasher#106]
ERROR: Encountered an error while flashing
argument of type 'NoneType' is not iterable

**Comment by badabing2005** [comment]
You expect to guess where and how this is happening?
Please provide a support file.

**Comment by floean** [comment]
> Вы рассчитываете догадаться, где и как это происходит? Пожалуйста, предоставьте файл поддержки.

where to get it?

**Comment by floean** [comment]
> You expect to guess where and how this is happening? Please provide a support file.

[support_2023-10-28_20-43-38.zip](https://github.com/badabing2005/PixelFlasher/files/13196191/support_2023-10-28_20-43-38.zip)

**Comment by badabing2005** [comment]
Unfortunately I don't have enough data in the logs to tell me exactly what is going wrong.
I can see that you are encountering an error when you click on the Flash Button.
Is that the case?
if yes, please take a screenshot before clicking flash, in case I case spot something in there.
Otherwise I'm afraid you'd have to wait for next release where I put additional debug messages to help me troubleshoot this, it's the first time I'm seeing this exact situation.

**Comment by badabing2005** [comment]
Reworked the flashing functionality. Please try version 6.0.0.0
If you encounter a problem, please provide a support file.
I'm closing this now, because I expect it to be resolved, but if you are still facing an issue, please post back and I'll reopen it.
