### ISSUE TITLE
REQUEST:  Default to "keep data" upon opening

### ISSUE THREAD

**Issue by Jon8RFC** [badabing2005/PixelFlasher#107]
I wiped an old device a few weeks ago and upon opening PixelFlasher.exe today to update a device, the "wipe all data" option was selected.

An accidental "keep data" is much less likely to be a detriment than an accidental "wipe all data".

Click-happy or tired clicking with a few minutes' wasted time on "keep data" and having to run it a second time is better than an irreversible "wipe all data".

**Comment by badabing2005** [comment]
The last settings are remembered and loaded on next startup by design.
I understand your concern, but there is a warning popup if you decide to proceed without changing that setting.
You can say the same thing for the force flag, it will cause a wipe if you keep it on, that too has a popup warning.

I want to keep the behavior consistent, and predictable, you might choose to set the wipe option, decide to quit without flashing, and come back to resume.

I might decide to change the behavior in the future, but this is currently not a priority.
Thanks for your feedback.

**Comment by Jon8RFC** [comment]
I follow.

Great app, and thanks for keeping it going!
