### ISSUE TITLE
[Future Request] avbroot

### ISSUE THREAD

**Issue by AK2H** [badabing2005/PixelFlasher#126]
can you please add avbroot automation to PixelFlasher to be able to lock the bootloader while maintaining root?
the main purpose of this suggestion is to pass Play Integrity checks without the need for fingerprint spoofing.

https://github.com/chenxiaolong/avbroot

> All Pixel devices with unlockable bootloaders support this

**Comment by Thisisauser6443** [comment]
> the main purpose of this suggestion is to pass Play Integrity checks without the need for fingerprint spoofing

Might be going slightly off-topic here, but this looks **VERY** interesting

**Comment by nyakze** [comment]
> main purpose of this suggestion is to pass Play Integrity checks without the need for fingerprint spoofing.
Except you can't pass play integrity with avbroot without fingerprint spoofing. It's used for security, not for passing PI.

**Comment by badabing2005** [comment]
At the moment, I have no plans in adding support to avbroot, not because I don't want to, I think it is a great project that I might use it myself, however given the additional inherent risks of bricking the device, I don't think this is something that people should take it lightly and use automated tools without understanding the process.
In its current state avbroot is for advanced users only, and beginner friendly tools like PixelFlasher hiding most of the complexities gives false sense of comfort.
