### ISSUE TITLE
Add feature

### ISSUE THREAD

**Issue by Bouteillepleine** [badabing2005/PixelFlasher#175]
Would be good to add the ability to hide Magisk (& rename it) as we have into the magisk application

**Comment by badabing2005** [comment]
It's possible with UIAutomator, as I'm not aware of any CLI or intent / activity / service based operations that would do that.
However UIAutomator is buggy, it doesn't work on all devices, it's not very reliable.
And even if I pulled it off, support would overwhelming.

I can take a quick look if there is a way, otherwise I won't consider this.

**Comment by badabing2005** [comment]
After careful look into this, It's not worth doing something like this with UIAutomator, specially when it is flaky.
