### ISSUE TITLE
pixel 6pro brick

### ISSUE THREAD

**Issue by llcary** [badabing2005/PixelFlasher#180]
Guys, please ask for help. I bought a 6pro. I got Android 14 when the 3.5 update. Then I flashed it with pixelfasher. The image is Android 14 when the in February update. After flashing, I cycled through the bl interface and restarted several times. The screen turned black and became bricked. Pressing nothing now has no effect,Can't enter fastboot mode, can't adb. Please save me.
and After I asked the pixel phone official, they suggested that I ask if you can solve this kind of problem.
ty

**Comment by badabing2005** [comment]
- No Need for tripple post.
- No need to start a new thread when there is a support thread.
- Github is for bugs and feature requests, not for support.

- And most importantly, have you read the guide? I'm inclined to think that you proceeded without reading, because had you done so, you would have known that the only way I can help you is by providing support file.
