### ISSUE TITLE
REQUEST:  clear data from %appdata%\PixelFlasher on Windows

### ISSUE THREAD

**Issue by Jon8RFC** [badabing2005/PixelFlasher#182]
Maybe I'm not seeing it somewhere, which certainly could be the case.

If not, an obvious option to clear out this data would be much appreciated rather than manually going and clearing out gigs worth of data every now and then.

If people aren't plainly aware of 20gigs, or more, worth of unwanted data being stored which they could erase, then it's not a helpful option if it's buried somewhere that they'd have to look for it or know to look for it.
Users need to be made aware that LOTS of unnecessary data could just be sitting there, hogging space.

A big, obnoxious button and a notification would be much appreciated.

**Comment by badabing2005** [comment]
You want some fries with that too?
There is an easy way to open the PixelFlasher working directory (from the menu as well as buttons).
You can even set the path for it so that it is written to an alternate drive.
There is even a smart delete button.(it keeps the factory / ota files around if there is any single dependency, if you delete the last boot / init_boot, it will also delete the factory / ota files)
It is up to the user to decide what they want to keep and what they want to get rid of.

This tool was never meant to be used without user putting any thought on what is being done behind the scenes.
When you did all this manually, who took care of your files?
Have you looked at other apps how much they write in there?
