### ISSUE TITLE
Difference in builds?

### ISSUE THREAD

**Issue by JohnLGalt** [badabing2005/PixelFlasher#189]
Hi, as a long time manual flasher via adb and fastboot, I'm just curious - I searched everywhere I could to find the difference ("2019") and only found one reference to it in all the release pages.

What exactly is the difference between the regular Windows release and the 2019 release? Running Windows 11 on one machine and Windows Server on another - I don't want to assume, but I thought it might be consumer OS versus Server OS....

**Comment by badabing2005** [comment]
PixelFlasher gets built on Github hosted runners,
The differences between the two builds is the base OS (hosted runner) that they get built on.
PixelFlasher_2019.exe is built on `windows-2019`
Whereas PixelFlasher.exe is built on `windows-latest`
You can read about them [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).
But why the two?
That's because Windows 7 can't run the latest Python, so for people running older Windows they use 2019 version (2019 is just reflecting the OS version it was built on).
You should be fine with `PixelFlasher.exe`
