### ISSUE TITLE
ADB not found even if it's there

### ISSUE THREAD

**Issue by ryder203** [badabing2005/PixelFlasher#2]
ADB is enabled on device in dev options and permitted, device is connected via USB, latest platform-tools are in place.
Flasher outputs error anyway. All the stuff is in C:\platform-tools ... The stuff in German that PowerShell gives me says:
_Suggestion [3,General]: The adb command was not found. However, it exists in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, type ".\adb" instead. For more information, see get-help about_Command_Precedence._

**Comment by badabing2005** [comment]
Ok, based on what you're telling me
You have a folder `c:\platform-tools`
All the adb stuff are in that folder
PixelFlasher.ps1 is in that folder and so is the factory image
You ran `./PixelFlasher.ps1` from Powershell prompt
While you were in that directory `c:\platform-tools` ?

If everything I said matches your scenario, would you be able to share the full output start till the error.

If I misunderstood your case, can provide details about what is exactly where, the Powershell prompt is running from which directory and what parameters were used? , actually providing the full output would answer all that because it's quite verbose about reporting what it find and doesn't.

Thanks for your feedback.

**Comment by ryder203** [comment]
Yes, right. I got C:\platform-tools - in there is all the ADB and fastboot stuff, plus your script and the factory image.
PowerShell gives me:
`PS C:\platform-tools> ./PixelFlasher.ps1
*******************************************************************************
PLEASE DO YOUR PART AND READ / SEARCH / RESEARCH BEFORE USING THIS SCRIPT
AND/OR ATTEMPTING ANY MODIFICATIONS TO YOUR DEVICE.
THIS TOOL ASSUMES THAT YOU ALREADY KNOW HOW TO AND HAVE ALREADY UNLOCKED
YOUR BOOTLOADER, ALREADY ROOTED YOUR DEVICE, HOW TO USE ANDROID SDK
PLATFORM-TOOLS, 7-ZIP, ETC.
THIS TOOL IS SIMPLY MY QUICK WAY OF UPDATING THE FIRMWARE WHILE ROOTED WITH
MAGISK, WITHOUT LOSING DATA / REQUIRING A WIPE.

MODIFYING YOUR DEVICE COMES WITH INHERENT RISKS, AND IT'S NOT MY RESPONSIBILITY
IF YOU LOSE YOUR DATA. THE SCRIPT I SHARE HAVE WORKED FOR ME, BUT THAT DOESN'T
MEAN THAT YOU MAY NOT RUN INTO PROBLEMS.  **BACKUP YOUR DATA.**
*******************************************************************************
PixelFlasher.ps1

cwd                       = C:\platform-tools
scriptPath                = C:\platform-tools
  Looking for platform-tools ...
adb not found

Error: adb is not installed or not in path.
       SDK Platform-Tools: is required ...
       You can find more info at: https://developer.android.com/studio/releases/platform-tools.html


Suggestion [3,General]: Der Befehl adb wurde nicht gefunden. Er ist jedoch am aktuellen Ort vorhanden. Windows PowerShell lädt Befehle nicht standardmäßig vom aktuellen Ort. Wenn Sie diesem Befehl vertrauen, geben Sie stattdessen ".\adb" ein. Weitere Informationen erhalten Sie unter "get-help about_Command_Precedence".
PS C:\platform-tools>`

**Comment by badabing2005** [comment]
Thank you @ryder203 
A silly oversight, Fixed.
