### ISSUE TITLE
Automate Device Fingerprint Testing for PIF

### ISSUE THREAD

**Issue by DavidBerdik** [badabing2005/PixelFlasher#208]
I think it would be incredibly useful to automate the testing of the random fingerprints returned by TheFreeman193's random PIF generator for people who don't want to go through the effort of manually testing prints.

The way I envision it working is fairly straightforward: continuously try fingerprints, run a tester app to check the result, and if the fingerprint does not pass BASIC and DEVICE, try again, otherwise, stop.

**Comment by badabing2005** [comment]
TheFreeman193 prints are all banned, and the repo hosting them has removed them.
The initially published Freeman193 prints had a mix of working and non-working prints, and this was by design by the author (rightfully so), the author could have published just the working prints, he knew which were working and which weren't.

If PixelFlasher fully automated the process and exposed just the working ones, it would have been against the wishes of the author and honestly mine too, the published set would have been banned much sooner.

The only way a print can survive such mass banning is by hunting for prints and testing them until you find one and never share it.
A tool that automates the process and makes it easy for everyone to find the same print defeats the purpose.

**Comment by DavidBerdik** [comment]
Fair enough. That makes sense to me.
