### ISSUE TITLE
Crashes on Pop!_OS 22.04 LTS

### ISSUE THREAD

**Issue by wunter8** [badabing2005/PixelFlasher#21]
When I run `./PixelFlasher-Linux`, it comes up with a bunch of `Gtk-WARNING`s. Then when I click on "Browse" to select the path to `platform-tools`, the program crashes. This is the output:

```
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/16x16/status/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: pango_attr_overline_new (gdk-pixbuf-error-quark, 5)
```

**Comment by badabing2005** [comment]
Yeah, so much for cross-platform.
Which PixelFlasher build did you try?
The Linux one is built on Ubuntu (I think 18.04) through Github actions and it was a major work to get it to build, which didn't work on Kali, hence why we have one for Kali (which I build manually locally for each release)
It is a PITA to get it build for each, this is mainly because of WxPython.

Can you try with Kali?
If that does not work, can you try the build steps?
I don't have Pop!_OS, and there does not seem to be wsl version for me to quickly setup.
I'll do my best to setup something, but no promises.

I do welcome pull requests, perhaps Github actions for Pop!_OS builds.

**Comment by wunter8** [comment]
I was using the Linux build. Since Pop!_OS 22 is based on Ubuntu, it's surprising that build didn't work. I just tried the Kali build, and it seems to work just fine on Pop!_OS 22. I ended up manually rooting my phone, so I can't go through the whole process with PixelFlasher right now, but I can get a lot farther using the Kali build than I did with the Linux build.

**Comment by badabing2005** [comment]
Thanks for the feedback, indeed it is surprising that Kali build worked better than the Ubuntu build, specially considering Pop!_OS being based on Ubuntu, however you're not the first one who had better success with Kali than Ubuntu.

For now I'll close the issue, if in the future you encounter issues with Kali, please either post to this ticket or create another one.

Thanks
