### ISSUE TITLE
"Android Platform Tools is not found" but they are in path and work otherwise. 

### ISSUE THREAD

**Issue by woubulbus** [badabing2005/PixelFlasher#210]
I am running the program in my downloads folder as administrator, and even though the program is added to my path (I can run adb in powershell or cmd in any folder), I cannot use most of the functionality of the program. This behavior happens on both my laptop and desktop, running Windows 11, and in a Windows Sandbox environment, in both user and system paths. Running "gcm adb" correctly shows that adb is located in C:\platform-tools\adb.exe.

The support file should be attached if I uploaded it correctly:
[support_2024-06-18_19-21-18.zip](https://github.com/user-attachments/files/15893676/support_2024-06-18_19-21-18.zip)

Let me know if more info is needed and what kind.

Edit: I confused myself and I thought that it was supposed to automatically find platform tools based on where its located on your path, but I cant find where it says this anymore and I might have made it up.

**Comment by badabing2005** [comment]
It was removed because it was causing more problems than it was helping.
People having an old version of it in their path (mostly without realizing) and because it was automatically got detected, they didn't even bother checking the platform tools requirements.
In any case that has been removed, (but it was still mentioned in the readme, I'll remove it from the readme in the next release)

One other thing, you shouldn't run it as admininstator.
