### ISSUE TITLE
just wondering?

### ISSUE THREAD

**Issue by shelby691** [badabing2005/PixelFlasher#22]
trying to install hentiaOS TwistedScarlett and cannot because Boot.img and Vendor.img are downloaded in separate files. how can i get around this? flasher wants to extract boot.img from full download. 
     thanks again, Shelb

**Comment by badabing2005** [comment]
Sorry I never heard about hentiaOS
You have any literature about this?
Is this a ROM?
What are the ROM Maker's instructions?
Link to the file(s)?

**Comment by shelby691** [comment]
https://www.patreon.com/posts/google-brooklyn-71125090?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator

**Comment by badabing2005** [comment]
What about the Installation guide?

**Comment by shelby691** [comment]
Sorry I didn't have it ready https://t.me/hentaiOSRaviole/3893

**Comment by badabing2005** [comment]
Can you please attach it here, I don't have Telegram account and don't plan to have one either.

**Comment by badabing2005** [comment]
You can give this approach a try, but be warned, I have no idea if it will work, I have not seen the ROM maker's guides and am only writing this based on what I have seen in those files.

1. Extract payload.bin from zip
2. Use [payload_dumper](https://github.com/vm03/payload_dumper) to extract the contents of payload.bin
3. zip the extracted contents (without payload.bin) and call it rom.zip or anything you want.
4. in PixelFlasher select firmware and choose the stock firmware applicable for your device that is compatible with this ROM (probably A12?)
5. In PixelFlasher Process firmware so that PixelFlasher extracts boot.img from it.
6. Not sure if you want to patch boot.img, check the ROM maker's instructions.
7. In PixelFlasher, choose `Apply Custom ROM` and select rom.zip
8. I don't know if you need to select `Disable Verity` and `Disable Verification` you'd have to check that with your ROM maker.
9. I also don't know if it requires Wipe or not.
10. Lastly Flash

I can't emphasize this enough, the steps above are just a guess, and I have no idea if it would work, for all I know it could brick your device, it is best to check the ROM maker's guides.
You have been warned.

**Comment by shelby691** [comment]
Thank you sir, I'll report the outcome ⏳️

**Comment by badabing2005** [comment]
Closing; no feedback.
