### ISSUE TITLE
Noob question: Can't patch

### ISSUE THREAD

**Issue by thund3rsh0ck** [badabing2005/PixelFlasher#223]
Have a Pixel 8, downloaded the latest image, shiba-ap2a.240705.005-factory-461aa7c8.zip.

I press process, and I hit the boot/init row, but the "Patch" button remains greyed out for some reason? Help?

Console shows that boot has been selected but Patched status is false, cause the button is greyed!
[support_2024-07-22_22-19-14.zip](https://github.com/user-attachments/files/16342954/support_2024-07-22_22-19-14.zip)

**Comment by thund3rsh0ck** [comment]
Okay apparently I solved this one myself, I had to install "Magisk" as an app first from the menu above, which wiped my phone somehow automatically, but allowed me to patch after that!

**Comment by badabing2005** [comment]
When you started using PixelFlasher, your device was in bootloader mode.
```
=======================================
Selected Device on 2024-07-22 22:17:54:
=======================================
    Device ID:                       REDACTED
    Device Model:                    shiba
    Device Active Slot:              a
    Device Mode:                     f.b
    Device Name:                     Pixel 8
    Device First API Level:          34
    Device Version End Date:         October 2030
    Device Security Update End Date: October 2030
    Has init_boot partition:         True
    Device Bootloader Version:       ripcurrent-14.5-11693900
    Device Unlocked:                 True
    slot-retry-count:a:              
    slot-unbootable:a:               
    slot-successful:a:               
    slot-retry-count:b:              
    slot-unbootable:b:               
    slot-successful:b:               
```
How do you expect to create a Patch in bootloader mode?
All you can do in that mode is flash, that is why Patch button was disabled.

As for installing Magisk and getting your phone wiped, are totally unrelated, not even close.
I have no idea as to what you did, because the support file that you provided does not have the actions you did after creating the support file.
