### ISSUE TITLE
Kubuntu 22.04.1 linux launch issues

### ISSUE THREAD

**Issue by eight85** [badabing2005/PixelFlasher#23]
Worked just fine on 22.04 but now crashes when attempting adjust any settings. Any advice or troubleshooting would be welcomed

**Comment by badabing2005** [comment]
Could you provide a support.zip (Help menu) file so that I can take a look?
Thanks

**Comment by eight85** [comment]
> Could you provide a support.zip (Help menu) file so that I can take a look? Thanks

It crashes before I'm able to make a sanitized support zip and but i have this log.

**Comment by eight85** [comment]
[PixelFlasher_2022-09-08_18h18m46s.log](https://github.com/badabing2005/PixelFlasher/files/9531170/PixelFlasher_2022-09-08_18h18m46s.log)

**Comment by badabing2005** [comment]
Looking at that log, it sounds like it is crashing when it outputs a dialog box about Android Platform tools being outdated.
Are you seeing the dialog?
This is weird one, because the dialog is like many other dialogs the application pops, actually the only difference is the message, the same function is called, so if the UI is not displayed, I'd have to ask you if anything changed in your environment?

If you run 3.6.0, does it still crash?
The dialog about Android Platform Tools being outdated will not be shown in 3.6.0 as that is a feature added in 3.7.0, however you can test other dialogs and see if they pop.

For example if you attempt to flash, it will first pop a dialog asking for confirmation.
Or if you select a factory image that is not a match for your device, you'd get a dialog.

By the way, you could also try generating support.zip using 3.6.0

**Comment by eight85** [comment]
Nothing has changed in my environment and I have done the following. The application opens but if I attempt to setup dir for platform tools it crashes, if I try to change settings or make a support zip it still crashes. I did attempt to use earlier builds including 3.6.0 before posting on here. Everything did work fine until upgrading Kubuntu from 22.04 to 22.04.1 I even tried a clean install on another computer with the same results.

**Comment by badabing2005** [comment]
> Everything did work fine until upgrading Kubuntu from 22.04 to 22.04.1
That's what I meant by anything have changed in your environment.
Definitely that could do it.
Which build are you trying with? Linux or Kali? many people have had better success running Kali version, even though the Linux version is built on Ubuntu. See #21 

You can also try the build steps if you're so inclined, if you manage to build it, then for sure it would work, the difficulty is with wxPython.

I'd appreciate if you report back.

**Comment by badabing2005** [comment]
@eight85 have you tried the Kali build?

**Comment by eight85** [comment]
Kali build works, should this be closed now?

**Comment by badabing2005** [comment]
Thanks for the update @eight85.
Closing the ticket.
