### ISSUE TITLE
Preserve migrate structure for readability when pushing PIF to device

### ISSUE THREAD

**Issue by V0latyle** [badabing2005/PixelFlasher#237]
After processing a print with osm0sis migrate script, structure is:
```
{
  // Build Fields
    "MANUFACTURER": "",
    "MODEL": "",
    "FINGERPRINT": "",
    "BRAND": "",
    "PRODUCT": "",
    "DEVICE": "",
    "RELEASE": "",
    "ID": "",
    "INCREMENTAL": "",
    "TYPE": "",
    "TAGS": "",
    "SECURITY_PATCH": "",
    "DEVICE_INITIAL_SDK_INT": "",

  // System Properties
    "*.build.id": "",
    "*.security_patch": "",
    "*api_level": "",

  // Advanced Settings
    "spoofBuild": "1",
    "spoofProps": "1",
    "spoofProvider": "1",
    "spoofSignature": "0",
    "verboseLogs": "0"
}
```

But Pixel Flasher modifies it when pushed to the device:
```
{
    "MANUFACTURER": "",
    "MODEL": "",
    "FINGERPRINT": "",
    "BRAND": "",
    "PRODUCT": "",
    "DEVICE": "",
    "RELEASE": "",
    "ID": "",
    "INCREMENTAL": "",
    "TYPE": "",
    "TAGS": "",
    "SECURITY_PATCH": "",
    "DEVICE_INITIAL_SDK_INT": "",
    "*.build.id": "",
    "*.security_patch": "",
    "*api_level": "",
    "spoofBuild": "1",
    "spoofProps": "1",
    "spoofProvider": "1",
    "spoofSignature": "0",
    "verboseLogs": "0"
}
```

Suggestion: Either update the way PF handles prints so they are always in the osm0sis strucure, or preserve formatting and structure when pushing to device

**Comment by badabing2005** [comment]
The differences are empty lines and comments.
Comments in json [are not supported](https://sentry.io/answers/comments-in-json/), they are only supported in [json5](https://spec.json5.org/)

Pifork happens to handle comments, but does not support full json5 specification, which goes beyond just comments.
Last I chhecked PIF by chiteroman, does not handle comments.

PixelFlasher to be most compatible, loads the file in json5 format, and then saves it in json format, this is why you see the comments and empty lines stripped, which is done by the json library.

Although it is possible to do some code changes to retain the format that PiFork migrate script produces, I can't use the json5 library to produce the output, because like I said, other features of json5 are not supported by the module (example: no quotes around key / value pairs, missing commas or extra commas ...) which means that I have to do some hacky coding and not use json / json 5 libraries and code parsing / producing the content.

I'm not sure if I want to take that path, as it makes the code less maintainable, and prone to bugs / regressions.

I'll keep this ticket open in case I can find a robust approach without making the code harder to maintain.

In an ideal world, PIF and PiFork would support json5 specs and use json5 libraries (which is easy in java but not sh), but I understand why that is not done, because in shell scripting it complicates the parsing of the payload without using tools like jq.

**Comment by V0latyle** [comment]
Thanks for pointing that out, I had no idea.
Sent via Gmail for Android

**Comment by badabing2005** [comment]
Added in 7.4.0.0
