### ISSUE TITLE
I get the unable to select device error

### ISSUE THREAD

**Issue by adipascu** [badabing2005/PixelFlasher#43]
The 10 second timeout is too slow for my Pixel 6. I'd like to see a UI prompt to go to the next step or just a longer timeout in general.

**Comment by badabing2005** [comment]
which 10 second timeout?
There are various waits in different parts of the program, please specify, or better yet provide a sanitized support.zip file from the help menu.

**Comment by adipascu** [comment]
Hello @badabing2005, nice to see you are so active :D

Here is a short console log with [support.zip](https://github.com/badabing2005/PixelFlasher/files/10304543/support.zip) attached.
```
==============================================================================
 2022-12-26 20:03:12 PixelFlasher 4.6.1.0              Flashing Phone    
==============================================================================
Rebooting device 18251FDF6008PD to bootloader ...
Waiting 10 seconds ...
2022-12-26 20:03:22 No Device is selected!

2022-12-26 20:03:22 ERROR: Unable to detect the device.
```
[**support.zip**](https://github.com/badabing2005/PixelFlasher/files/10304543/support.zip)

I've also tried building the linux version for Ubuntu 22.04 to do the changes myself and failed because of issues with wxPython.

**Comment by badabing2005** [comment]
Looking at your logs, I don't think your issue is timing.
I also have a Pixel 6 device, and even 5 seconds is enough.
When the phone is rebooted to bootloader mode, and no device is detected after waiting 10 seconds.
please open a terminal and type
```
/home/adi/Android/Sdk/platform-tools/fastboot devices
```
see if your device is detected.
if it is detected in the terminal, do a scan of devices in PF
it should be detected in fastboot mode (bootloader)

You can click on the flash at that point.
But I suspect when your phone is in bootloader mode (and that if it is in that mode) the device is not detected.
I see your phone being in recovery mode instead of bootloader mode,

**Comment by adipascu** [comment]
@badabing2005 you are right, it was not a timeout issue but a permission issue.
`fastboot` required root permission to do it's thing.

**Comment by badabing2005** [comment]
Happy to learn that you resolved the issue
