### ISSUE TITLE
Pixel Flasher hangs right after clicking "Flash Pixel Phone"

### ISSUE THREAD

**Issue by Micha3lo** [badabing2005/PixelFlasher#45]
Just as in a title, pixel flasher straight up hangs right after clicking a flashing button. My OS is OpenSUSE Tumbleweed and I'm using a Kali build (as Ubuntu build throws me an error about outdated adb and fastboot). My phone reboots to bootloader just fine after i click the flashing button, but that's where the program hangs and nothing else happens after.

**Comment by badabing2005** [comment]
I suspect that after rebooting to bootloader mode, the device is no longer detected.
In a terminal please type `fastboot device` and see if it lists your device.
Providing a sanitized support.zip (from the help menu) goes a long way towards troubleshooting the issue.

**Comment by Micha3lo** [comment]
I have tried rebooting to bootloader mode, then typed `fastboot devices` and it shows my phone just fine. I also wanna add that simply clicking on `Reboot to Bootloader` in Pixel Flasher simply hangs the program and it's not usable anymore, unless killed.

Here's a support.zip file
[support.zip](https://github.com/badabing2005/PixelFlasher/files/10368089/support.zip)

**Comment by badabing2005** [comment]
Looking at the logs, it looks like it is never getting past `time.sleep(10)` python command.
This is really weird, as that command should not hang, it's a first I've seen.

Try this.
Reboot to bootloader first (manually)
Scan for devices in PF, it should detect the device in bootloader mode.
Then hit the flash button, it will skip the part to reboot to bootloader and wait, and go straight to flashing.
See if that works.

**Comment by Micha3lo** [comment]
I really feel like there is something wrong with my setup, whenever I try to open Pixel Flasher after going to bootloader then plugging my phone, it never really opens, it just hangs on the loading screen. I have also noticed via `top` that fastboot is using a lot of CPU (being the first process) whenever my phone is in such setup, really weird.

**Comment by Micha3lo** [comment]
Alright so, I did some progress and I've decided to use android-tools right from OBS repository (instead of Google's website) and now Pixel Flasher doesn't hang anymore, BUT whenever my phone goes to fastboot, PF doesn't detect it anymore throwing
`2023-01-08 22:09:41 ERROR: Unable to detect the device.`
Checking my phone via `fastboot devices` however shows it just fine

Attaching 
[support.zip](https://github.com/badabing2005/PixelFlasher/files/10369491/support.zip) again just in case

**Comment by badabing2005** [comment]
Happy to hear that you resolved the issue.

I think this was your issue.
```
2023-01-08 22:01:32 ERROR: The selected path /usr/share/doc/packages/android-tools does not have adb and or fastboot
Looking for Android Platform Tools in system PATH environment ...
Found Android Platform Tools in /usr/bin
```

You selected a path that did not have adb or fastboot, probably fastboot since you were able to reboot using adb.
Then PF tried to look into your path to see if there was any, and it found in /usr/bin (possibly very old version installed through Linux Package Manager)

It's best to hunt for all versions of adb / fastboot (first kill any adb / fastboot processes that are still lingering around) and delete / uninstall.
Then download the latest from Google (just click on PF link which should take you to the latest)
You can unpack that anywhere that would be accessible to PF.
I think you should be fine.

I'll close this issue now, but if you run into issues don't hesitate to open another ticket.
