### ISSUE TITLE
Pixel 7 May Update Issues

### ISSUE THREAD

**Issue by MEDumont** [badabing2005/PixelFlasher#68]
Hi, let me start by saying I love the PixelFlasher utility. It makes rooting way less of a headache. I was getting nagged by my rooted phone about the May security update, so I decided to try and flash it. Unfortunately, I botched it up and accidentally flashed a full unpatched image. Now, when I try to flash the patched image, it says it is rooted, but Magisk is not showing as installed and the phone isn't rooted when the process completes, though PixelFlasher thinks it is. Magisk does not prompt me to finish installation either. It just says it isn't installed. It says that it was patched with Magisk 25.2, but the actual version installed in 26.1. Is there any way to get re-rooted? Thanks in advance!

**Comment by MEDumont** [comment]
I've also tried reverting to the old patched image (February security update), and it won't boot if I do that.

**Comment by MEDumont** [comment]
Nevermind, I'm a walking 1D10T error. I was able to resolve by installing the special 25.2 version in the app, then disabling some incompatible modules, and repatching.

**Comment by badabing2005** [comment]
Thanks for the kind words,
By the way this is a known issue, the most likely reason behind it is that you have a hidden Magisk along with a non-hidden one, PF thinks it's rooted, because it is indeed it is rooted, otherwise there is no way for PF to think so, because it executes root commands to determine that, and if you were not rooted it would have definitely failed.
The fix is to uninstall the hidden Magisk and reboot, then the un-hidden one will say that you are rooted.
At that point if you wish you can hide it again.
