### ISSUE TITLE
Unzip of march factory image fails

### ISSUE THREAD

**Issue by Dart2112** [badabing2005/PixelFlasher#9]
Logs as below

```
Preparing Package

Found Bundled 7zip.

zip/unzip operations will be faster

Unzipping Image: C:\Android\PixelFlasher\oriole-sp2a.220305.013.a3-factory-8bea92d1.zip into C:\Android\PixelFlasher ...

Unzip time1: 0.11537671089172363

ERROR: Unzipped folder oriole-sp2a.220305.013.a3 not found.

Aborting ...

```
There is no unzipped content in the folder so something isn't right. I've tried it both in a folder on my desktop and in the android folder with the same results

**Comment by badabing2005** [comment]
Thanks for reporting.
I can't reproduce this, but if I'd have to take a guess it looks like for whatever reasons the bundled 7zip is not extracting the zip properly, just to be certain, are you able to unzip the file manually without any errors? This is to eliminate the possibility of the zip file being corrupt.
Later today, I'll update the program to have the option of turning off the use of bundled 7zip and instead use python libraries to unzip (the slow way), I'll also add more verbose logging option so that it helps with troubleshooting.

**Comment by Dart2112** [comment]
It's not a corrupt file cause I used it to manually update

**Comment by badabing2005** [comment]
Would you be able to try it with v1.1.4-alpha just posted?
It handles spaces in any path.
I'll work on zip disabling next if this doesn't resolve your issue.

**Comment by badabing2005** [comment]
@Dart2112 
I think this should address your issue.
https://github.com/badabing2005/PixelFlasher/releases/tag/v1.1.5-alpha

**Comment by badabing2005** [comment]
This is fixed.
