### ISSUE TITLE
"Unable to detect the device" on recent versions

### ISSUE THREAD

**Issue by leonbeon** [badabing2005/PixelFlasher#95]
When trying to update my Pixel 6 to the August update, I get the following error after the device loads into the bootloader. The application is stuck and exits with the following console message:
```
==============================================================================
 2023-09-02 17:15:40 PixelFlasher 5.7.2.0              Flashing Phone    
==============================================================================
Android Platform Tools Version: 33.0

.3-8952118
Rebooting device 19041FDF60034J to bootloader ...
Waiting 10 seconds ...

2023-09-02 17:15:57 No Device is selected!

2023-09-02 17:15:57 ERROR: Unable to detect the device.
Waiting 10 seconds ...
2023-09-02 17:16:07 No Device is selected!

2023-09-02 17:16:07 ERROR: Unable to detect the device.
```

On the phone, the usual bootloader screen is visible, but nothing happens afterwards.

This happened a few weeks back as well. I thought it was a fluke back then and waited, but it's the same error. I'm using PixelFlasher v5.7.2.0. I've attached the support.zip here: [support_2023-09-02_17-16-47.zip](https://github.com/badabing2005/PixelFlasher/files/12504221/support_2023-09-02_17-16-47.zip)

**Comment by badabing2005** [comment]
This sounds like USB driver issue.
When the phone reboots to bootloader mode, so that it can be flashed, the phone is not detected by your computer.
Check the Google USB driver link in the help menu, install that.
Make sure when you type on a command windows `fastboot devices` you see your device online, that would be a sign that the drivers are working.

You can also try different cable, different USB port (usually USB 2.0 works better)

**Comment by leonbeon** [comment]
Ah yes, I recently updated from Win10 to Win11, neglecting to re-install the USB drivers. That fixed it, thank you!
